// export const FETCH_ARTICLES_BY_CLASSANDPAGE = "FETCH_ARTICLES_BY_CLASSANDPAGE";

// export const FETCH_ARTICLES_BY_KEYWORD = "FETCH_ARTICLES_BY_KEYWORD";

// export const DELETE_ARTICLE = "DELETE_ARTICLE";

export const FETCH_ARTICLES_BYCLASSANDPAGE_START = "FETCH_ARTICLES_BYCLASSANDPAGE_START";

export const FETCH_FIRSTPAGEARTICLE_BYCLASS_START = "FETCH_FIRSTPAGEARTICLE_BYCLASS_START";

export const FETCH_FIRSTPAGEARTICLE_BYCLASS_FINISH = "FETCH_FIRSTPAGEARTICLE_BYCLASS_FINISH";

export const FETCH_ARTICLES_BYCLASSANDPAGE_FINISH = "FETCH_ARTICLES_BYCLASSANDPAGE_FINISH";

export const FETCH_ARTICLES_BYCLASSANDPAGE_ERROR = "FETCH_ARTICLES_BYCLASSANDPAGE_ERROR";

export const CHANGE_PAGE = "CHANGE_PAGE";