export const ADD_CLASS = "ADD_CLASS";

export const REMOVE_CLASS = "REMOVE_CLASS";

export const EDIT_CLASS = "EDIT_CLASS";

export const FETCH_CLASSES = "FETCH_CLASSES";

export const FETCH_CLASSES_START = "FETCH_CLASSES_START";

export const FETCH_CLASSES_FINISH = "FETCH_CLASSES_FINISH";

export const FETCH_CLASSES_ERROR = "FETCH_CLASSES_ERROR";

export const ADD_CLASS_START = "ADD_CLASS_START";

export const ADD_CLASS_FINISH = "ADD_CLASS_FINISH";

export const ADD_CLASS_ERROR = "ADD_CLASS_ERROR";

export const REMOVE_CLASS_START = "REMOVE_CLASS_START";

export const REMOVE_CLASS_FINISH = "REMOVE_CLASS_FINISH";

export const REMOVE_CLASS_ERROR = "REMOVE_CLASS_ERROR";

export const EDIT_CLASS_START = "EDIT_CLASS_START";

export const EDIT_CLASS_FINISH = "EDIT_CLASS_FINISH";

export const EDIT_CLASS_ERROR = "EDIT_CLASS_ERROR";